version: "2"
services:
  app:
    container_name: rest-node-app
    restart: always
    build: .
    ports:
      - "80:8080"
    links:
      - rest-mongo
  rest-mongo:
    container_name: rest-mongo
    image: mongo
    ports:
      - "27017:27017"